# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wiimote.ui'
#
# Created: Sun May 20 16:33:56 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 611)
        MainWindow.setMinimumSize(QtCore.QSize(334, 609))
        MainWindow.setWindowTitle("Swiim")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connection = QtGui.QGroupBox(self.centralwidget)
        self.connection.setObjectName("connection")
        self.horizontalLayout = QtGui.QHBoxLayout(self.connection)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connect = QtGui.QPushButton(self.connection)
        self.connect.setObjectName("connect")
        self.horizontalLayout_3.addWidget(self.connect)
        self.disconnect = QtGui.QPushButton(self.connection)
        self.disconnect.setObjectName("disconnect")
        self.horizontalLayout_3.addWidget(self.disconnect)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.connection)
        self.wiimote = QtGui.QGroupBox(self.centralwidget)
        self.wiimote.setEnabled(True)
        self.wiimote.setObjectName("wiimote")
        self._2 = QtGui.QFormLayout(self.wiimote)
        self._2.setObjectName("_2")
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName("_3")
        self.control = QtGui.QVBoxLayout()
        self.control.setObjectName("control")
        self.controlRumble = QtGui.QPushButton(self.wiimote)
        self.controlRumble.setText("Toggle Rumble")
        self.controlRumble.setObjectName("controlRumble")
        self.control.addWidget(self.controlRumble)
        self.label_2 = QtGui.QLabel(self.wiimote)
        self.label_2.setText("Set LEDs")
        self.label_2.setObjectName("label_2")
        self.control.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlLed1 = QtGui.QCheckBox(self.wiimote)
        self.controlLed1.setText("")
        self.controlLed1.setChecked(False)
        self.controlLed1.setObjectName("controlLed1")
        self.horizontalLayout_2.addWidget(self.controlLed1)
        self.controlLed2 = QtGui.QCheckBox(self.wiimote)
        self.controlLed2.setText("")
        self.controlLed2.setObjectName("controlLed2")
        self.horizontalLayout_2.addWidget(self.controlLed2)
        self.controlLed3 = QtGui.QCheckBox(self.wiimote)
        self.controlLed3.setText("")
        self.controlLed3.setObjectName("controlLed3")
        self.horizontalLayout_2.addWidget(self.controlLed3)
        self.controlLed4 = QtGui.QCheckBox(self.wiimote)
        self.controlLed4.setText("")
        self.controlLed4.setObjectName("controlLed4")
        self.horizontalLayout_2.addWidget(self.controlLed4)
        self.control.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.control.addItem(spacerItem1)
        self._3.addLayout(self.control)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self._3.addItem(spacerItem2)
        self.status = QtGui.QVBoxLayout()
        self.status.setObjectName("status")
        self.wiimoteImageHolder = QtGui.QWidget(self.wiimote)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wiimoteImageHolder.sizePolicy().hasHeightForWidth())
        self.wiimoteImageHolder.setSizePolicy(sizePolicy)
        self.wiimoteImageHolder.setMinimumSize(QtCore.QSize(177, 450))
        self.wiimoteImageHolder.setMaximumSize(QtCore.QSize(177, 450))
        self.wiimoteImageHolder.setObjectName("wiimoteImageHolder")
        self.wiimoteImage = QtGui.QLabel(self.wiimoteImageHolder)
        self.wiimoteImage.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.wiimoteImage.setText("")
        self.wiimoteImage.setPixmap(QtGui.QPixmap("images/wiimote.png"))
        self.wiimoteImage.setObjectName("wiimoteImage")
        self.btnA = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnA.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnA.setText("")
        self.btnA.setPixmap(QtGui.QPixmap("images/a.png"))
        self.btnA.setObjectName("btnA")
        self.btnB = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnB.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnB.setText("")
        self.btnB.setPixmap(QtGui.QPixmap("images/b.png"))
        self.btnB.setObjectName("btnB")
        self.btn1 = QtGui.QLabel(self.wiimoteImageHolder)
        self.btn1.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btn1.setText("")
        self.btn1.setPixmap(QtGui.QPixmap("images/1.png"))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtGui.QLabel(self.wiimoteImageHolder)
        self.btn2.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btn2.setText("")
        self.btn2.setPixmap(QtGui.QPixmap("images/2.png"))
        self.btn2.setObjectName("btn2")
        self.btnMinus = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnMinus.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnMinus.setText("")
        self.btnMinus.setPixmap(QtGui.QPixmap("images/minus.png"))
        self.btnMinus.setObjectName("btnMinus")
        self.btnPlus = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnPlus.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnPlus.setText("")
        self.btnPlus.setPixmap(QtGui.QPixmap("images/plus.png"))
        self.btnPlus.setObjectName("btnPlus")
        self.btnHome = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnHome.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnHome.setText("")
        self.btnHome.setPixmap(QtGui.QPixmap("images/home.png"))
        self.btnHome.setObjectName("btnHome")
        self.btnUp = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnUp.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnUp.setText("")
        self.btnUp.setPixmap(QtGui.QPixmap("images/up.png"))
        self.btnUp.setObjectName("btnUp")
        self.btnRight = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnRight.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnRight.setText("")
        self.btnRight.setPixmap(QtGui.QPixmap("images/right.png"))
        self.btnRight.setObjectName("btnRight")
        self.btnDown = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnDown.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnDown.setText("")
        self.btnDown.setPixmap(QtGui.QPixmap("images/down.png"))
        self.btnDown.setObjectName("btnDown")
        self.btnLeft = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnLeft.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnLeft.setText("")
        self.btnLeft.setPixmap(QtGui.QPixmap("images/left.png"))
        self.btnLeft.setObjectName("btnLeft")
        self.led1 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led1.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led1.setText("")
        self.led1.setPixmap(QtGui.QPixmap("images/led1.png"))
        self.led1.setObjectName("led1")
        self.led4 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led4.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led4.setText("")
        self.led4.setPixmap(QtGui.QPixmap("images/led4.png"))
        self.led4.setObjectName("led4")
        self.led3 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led3.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led3.setText("")
        self.led3.setPixmap(QtGui.QPixmap("images/led3.png"))
        self.led3.setObjectName("led3")
        self.led2 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led2.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led2.setText("")
        self.led2.setPixmap(QtGui.QPixmap("images/led2.png"))
        self.led2.setObjectName("led2")
        self.status.addWidget(self.wiimoteImageHolder)
        self.label = QtGui.QLabel(self.wiimote)
        self.label.setText("Battery")
        self.label.setObjectName("label")
        self.status.addWidget(self.label)
        self.statusBattery = QtGui.QProgressBar(self.wiimote)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBattery.sizePolicy().hasHeightForWidth())
        self.statusBattery.setSizePolicy(sizePolicy)
        self.statusBattery.setAutoFillBackground(False)
        self.statusBattery.setProperty("value", 0)
        self.statusBattery.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.statusBattery.setObjectName("statusBattery")
        self.status.addWidget(self.statusBattery)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.status.addItem(spacerItem3)
        self._3.addLayout(self.status)
        self._2.setLayout(0, QtGui.QFormLayout.LabelRole, self._3)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.setItem(0, QtGui.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout.addWidget(self.wiimote)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.connection.setTitle(QtGui.QApplication.translate("MainWindow", "Wiimote Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.wiimote.setTitle(QtGui.QApplication.translate("MainWindow", "Wiimote Control", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

