# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wiimote_test.ui'
#
# Created: Sat May 26 19:58:27 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.7
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wiimoteTestQWidget(object):
    def setupUi(self, wiimoteTestQWidget):
        wiimoteTestQWidget.setObjectName("wiimoteTestQWidget")
        wiimoteTestQWidget.resize(387, 522)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(wiimoteTestQWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBoxLayout = QtGui.QVBoxLayout()
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.connectionGroup = QtGui.QGroupBox(wiimoteTestQWidget)
        self.connectionGroup.setObjectName("connectionGroup")
        self.horizontalLayout = QtGui.QHBoxLayout(self.connectionGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.disconnect = QtGui.QPushButton(self.connectionGroup)
        self.disconnect.setObjectName("disconnect")
        self.horizontalLayout.addWidget(self.disconnect)
        self.connect = QtGui.QPushButton(self.connectionGroup)
        self.connect.setObjectName("connect")
        self.horizontalLayout.addWidget(self.connect)
        self.groupBoxLayout.addWidget(self.connectionGroup)
        self.wiimoteGroup = QtGui.QGroupBox(wiimoteTestQWidget)
        self.wiimoteGroup.setEnabled(True)
        self.wiimoteGroup.setObjectName("wiimoteGroup")
        self.verticalLayout = QtGui.QVBoxLayout(self.wiimoteGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.controlRumble = QtGui.QPushButton(self.wiimoteGroup)
        self.controlRumble.setText("Toggle Rumble")
        self.controlRumble.setObjectName("controlRumble")
        self.verticalLayout.addWidget(self.controlRumble)
        self.label_2 = QtGui.QLabel(self.wiimoteGroup)
        self.label_2.setText("Set LEDs")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlLed1 = QtGui.QCheckBox(self.wiimoteGroup)
        self.controlLed1.setText("")
        self.controlLed1.setChecked(False)
        self.controlLed1.setObjectName("controlLed1")
        self.horizontalLayout_2.addWidget(self.controlLed1)
        self.controlLed2 = QtGui.QCheckBox(self.wiimoteGroup)
        self.controlLed2.setText("")
        self.controlLed2.setObjectName("controlLed2")
        self.horizontalLayout_2.addWidget(self.controlLed2)
        self.controlLed3 = QtGui.QCheckBox(self.wiimoteGroup)
        self.controlLed3.setText("")
        self.controlLed3.setObjectName("controlLed3")
        self.horizontalLayout_2.addWidget(self.controlLed3)
        self.controlLed4 = QtGui.QCheckBox(self.wiimoteGroup)
        self.controlLed4.setText("")
        self.controlLed4.setObjectName("controlLed4")
        self.horizontalLayout_2.addWidget(self.controlLed4)
        spacerItem = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBoxLayout.addWidget(self.wiimoteGroup)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.groupBoxLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.groupBoxLayout)
        self.wiimoteLayout = QtGui.QVBoxLayout()
        self.wiimoteLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.wiimoteLayout.setObjectName("wiimoteLayout")
        self.wiimoteImageHolder = QtGui.QWidget(wiimoteTestQWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wiimoteImageHolder.sizePolicy().hasHeightForWidth())
        self.wiimoteImageHolder.setSizePolicy(sizePolicy)
        self.wiimoteImageHolder.setMinimumSize(QtCore.QSize(177, 450))
        self.wiimoteImageHolder.setMaximumSize(QtCore.QSize(177, 450))
        self.wiimoteImageHolder.setObjectName("wiimoteImageHolder")
        self.wiimoteImage = QtGui.QLabel(self.wiimoteImageHolder)
        self.wiimoteImage.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.wiimoteImage.setText("")
        self.wiimoteImage.setPixmap(QtGui.QPixmap("images/wiimote.png"))
        self.wiimoteImage.setObjectName("wiimoteImage")
        self.btnA = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnA.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnA.setText("")
        self.btnA.setPixmap(QtGui.QPixmap("images/a.png"))
        self.btnA.setObjectName("btnA")
        self.btnB = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnB.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnB.setText("")
        self.btnB.setPixmap(QtGui.QPixmap("images/b.png"))
        self.btnB.setObjectName("btnB")
        self.btn1 = QtGui.QLabel(self.wiimoteImageHolder)
        self.btn1.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btn1.setText("")
        self.btn1.setPixmap(QtGui.QPixmap("images/1.png"))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtGui.QLabel(self.wiimoteImageHolder)
        self.btn2.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btn2.setText("")
        self.btn2.setPixmap(QtGui.QPixmap("images/2.png"))
        self.btn2.setObjectName("btn2")
        self.btnMinus = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnMinus.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnMinus.setText("")
        self.btnMinus.setPixmap(QtGui.QPixmap("images/minus.png"))
        self.btnMinus.setObjectName("btnMinus")
        self.btnPlus = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnPlus.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnPlus.setText("")
        self.btnPlus.setPixmap(QtGui.QPixmap("images/plus.png"))
        self.btnPlus.setObjectName("btnPlus")
        self.btnHome = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnHome.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnHome.setText("")
        self.btnHome.setPixmap(QtGui.QPixmap("images/home.png"))
        self.btnHome.setObjectName("btnHome")
        self.btnUp = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnUp.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnUp.setText("")
        self.btnUp.setPixmap(QtGui.QPixmap("images/up.png"))
        self.btnUp.setObjectName("btnUp")
        self.btnRight = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnRight.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnRight.setText("")
        self.btnRight.setPixmap(QtGui.QPixmap("images/right.png"))
        self.btnRight.setObjectName("btnRight")
        self.btnDown = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnDown.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnDown.setText("")
        self.btnDown.setPixmap(QtGui.QPixmap("images/down.png"))
        self.btnDown.setObjectName("btnDown")
        self.btnLeft = QtGui.QLabel(self.wiimoteImageHolder)
        self.btnLeft.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.btnLeft.setText("")
        self.btnLeft.setPixmap(QtGui.QPixmap("images/left.png"))
        self.btnLeft.setObjectName("btnLeft")
        self.led1 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led1.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led1.setText("")
        self.led1.setPixmap(QtGui.QPixmap("images/led1.png"))
        self.led1.setObjectName("led1")
        self.led4 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led4.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led4.setText("")
        self.led4.setPixmap(QtGui.QPixmap("images/led4.png"))
        self.led4.setObjectName("led4")
        self.led3 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led3.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led3.setText("")
        self.led3.setPixmap(QtGui.QPixmap("images/led3.png"))
        self.led3.setObjectName("led3")
        self.led2 = QtGui.QLabel(self.wiimoteImageHolder)
        self.led2.setGeometry(QtCore.QRect(0, 0, 177, 450))
        self.led2.setText("")
        self.led2.setPixmap(QtGui.QPixmap("images/led2.png"))
        self.led2.setObjectName("led2")
        self.wiimoteLayout.addWidget(self.wiimoteImageHolder)
        self.label = QtGui.QLabel(wiimoteTestQWidget)
        self.label.setText("Battery")
        self.label.setObjectName("label")
        self.wiimoteLayout.addWidget(self.label)
        self.statusBattery = QtGui.QProgressBar(wiimoteTestQWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBattery.sizePolicy().hasHeightForWidth())
        self.statusBattery.setSizePolicy(sizePolicy)
        self.statusBattery.setAutoFillBackground(False)
        self.statusBattery.setProperty("value", 0)
        self.statusBattery.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.statusBattery.setObjectName("statusBattery")
        self.wiimoteLayout.addWidget(self.statusBattery)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.wiimoteLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.wiimoteLayout)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)

        self.retranslateUi(wiimoteTestQWidget)
        QtCore.QMetaObject.connectSlotsByName(wiimoteTestQWidget)

    def retranslateUi(self, wiimoteTestQWidget):
        self.connectionGroup.setTitle(QtGui.QApplication.translate("wiimoteTestQWidget", "Wiimote Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect.setText(QtGui.QApplication.translate("wiimoteTestQWidget", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setText(QtGui.QApplication.translate("wiimoteTestQWidget", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.wiimoteGroup.setTitle(QtGui.QApplication.translate("wiimoteTestQWidget", "Wiimote Control", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    wiimoteTestQWidget = QtGui.QWidget()
    ui = Ui_wiimoteTestQWidget()
    ui.setupUi(wiimoteTestQWidget)
    wiimoteTestQWidget.show()
    sys.exit(app.exec_())

